app:
  # string for main window`s title
  title: This is a title

  # main window`s icon relative path
  iconPath: /test-img/r.png

  # splash image relative path
  splashImgPath:

  # is splash progress bar shown (false/true, off/on. 0/1)
  splashProgressBar: false

  # full class name which extends the AppInitThread super class
  initThread: scipiofx.test.TestInitThread

  # full class name which implemented the launch listener interface
  launchListener:

  # view`s config
  view:
    # main window`s content fxml relative path
    mainViewPath: /test-views/main.fxml
    # javafx.stage.StageStyle (both lower case and upper case can be accepted)
    stageStyle: decorated
    # is main window can be draggable by any position (false/true, off/on. 0/1)
    draggable: true
    # is main window can be resizable to any size of window (false/true, off/on. 0/1)
    resizable: false
    # default view id (it`s just an integrated support for developer, not meaning the framework will auto switch to this view)
    defaultViewId: 1

  # MaterialFX theme config
  materialFx:
    # Determine whether to enable the materialfx theme or not
    enable: true
    # Determine whether to init the materialfx theme only or not
    useMaterialFxThemeOnly: false
    # Include the legacy materialfx theme or not (and the javafx original theme will be effected too)
    includeLegacy: true
    # Declare the materialfx initializer class (full class name, or empty to use default initializer when using materialfx)
    initializer:

mybatis:
  # mapper.xml
  mappersLocation: mappers/
  # mapper.java
  mapperPackages:
    - scipiofx.test.db.dao
  # entity.java
  typeAliases:
    - scipiofx.test.db.entity
  # datasource
  connects:
    dataSource0:
      driverClass: com.mysql.cj.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/abc?useSSL=false&serverTimezone=GMT%2B8&
      username: root
      password: password

#custom root config property for test
custom:
  testA: asd